### PR TITLE
Fix all golint and vet errors

### LINKED ISSUE #121: Linting overhaul of Go code
Working with the code in its current state makes it hard to spot errors for all the linting warnings.

I propose a refactor where all linting warnings are mitigated and, hopefully, a `go vet` step once #114 is merged.

### PR DESCRIPTION
**Pull request by sirlatrom**
Fixes #121.

### CODE REVIEW

File: restapi/datasource_api_object.go [hunk 1]
```diff
@@ -1,57 +1,58 @@
...
 )
 
-func dataSourceRestApi() *schema.Resource {
+func dataSourceRestAPI() *schema.Resource {
 	return &schema.Resource{
-		Read: dataSourceRestApiRead,
+		Read: dataSourceRestAPIRead,
 
 		Schema: map[string]*schema.Schema{
-			"path": &schema.Schema{
```
Comment (DRuggeri) [inline restapi/datasource_api_object.go:13]: What is the affect of changing this? I'm assuming nothing since the map is declared to be a set of schema pointers keyed on a string... is this just shorthand? I ask because the Terraform provider docs suggested this format so I just rolled with it.

File: restapi/resource_api_object.go [hunk 2]
```diff
@@ -131,10 +133,10 @@ func resourceRestApi() *schema.Resource {
    than the "id" passed on the command line, we have to use an opinionated
    view of the API paths to figure out how to read that object
    from the API */
-func resourceRestApiImport(d *schema.ResourceData, meta interface{}) (imported []*schema.ResourceData, err error) {
+func resourceRestAPIImport(d *schema.ResourceData, meta interface{}) (imported []*schema.ResourceData, err error) {
 	input := d.Id()
 
-	hasTrailingSlash := strings.LastIndex(input, "/") == len(input)-1
```
Comment (DRuggeri) [inline restapi/resource_api_object.go:137]: I like these - good call :-)

**Comment by DRuggeri** [comment]
Thanks, so much for the pull request @sirlatrom! This is great - anything that cleans up the codebase is a welcome change. I'm a little overwhelmed by the number of changes as you can imagine, but my review of the modifications indicates no problem.

My only reservation is the change from snake_case to camelCase. I had used snake_case because it aligned with the format terraform used - though that frankly doesn't matter much so I don't mind the change.

Can you share a little more information of how the diff was generated, what go vet errors you were seeing, and how you had used go lint to identify issues? I'd like to incorporate such checks into [the release script](https://github.com/Mastercard/terraform-provider-restapi/blob/master/scripts/do_release.sh) to ensure a release isn't made that contains issues.

**Comment by sirlatrom** [comment]
> 
> 
> Thanks, so much for the pull request @sirlatrom! This is great - anything that cleans up the codebase is a welcome change. I'm a little overwhelmed by the number of changes as you can imagine, but my review of the modifications indicates no problem.
> 
> My only reservation is the change from snake_case to camelCase. I had used snake_case because it aligned with the format terraform used - though that frankly doesn't matter much so I don't mind the change.
> 
> Can you share a little more information of how the diff was generated, what go vet errors you were seeing, and how you had used go lint to identify issues? I'd like to incorporate such checks into [the release script](https://github.com/Mastercard/terraform-provider-restapi/blob/master/scripts/do_release.sh) to ensure a release isn't made that contains issues.

Yes, certainly. The snake_case to camelCase is to make the code more Go-idiomatic. Notice that the Terraform resource, attribute , etc. names are unaffected by this.

The diff was based on me running `got vet ./...` and [`golint -set_exit_status ./...`](https://github.com/golang/lint) and working through all warnings they produced.

**Comment by DRuggeri** [comment]
This is great - I really appreciate it! I just made a few enhancements that I've had in the backlog a while and would like to work through some other existing PRs. Do you mind adjusting this PR to fix merge conflicts afterwards? I'd like to include this as part of the next release since clean code is something worth bragging about!

**Comment by sirlatrom** [comment]
> 
> 
> This is great - I really appreciate it! I just made a few enhancements that I've had in the backlog a while and would like to work through some other existing PRs. Do you mind adjusting this PR to fix merge conflicts afterwards? I'd like to include this as part of the next release since clean code is something worth bragging about!

Sure thing, let me know when you're done and I can start looking at whatever are the remaining vet and golint issues.

**Comment by DRuggeri** [comment]
I think we're all set with code updates for now, @sirlatrom. Thanks!

**Comment by sirlatrom** [comment]
@DRuggeri OK, this should do it. I can see that some additional checks I've followed were done by https://github.com/dominikh/go-staticcheck, which looks like it's installed by default in VS Code when you run then `Go: Install/Update tools` command. You may consider adding that as yet another linter in your upcoming GitHub Actions.

**Comment by DRuggeri** [comment]
Love it! Thanks, @sirlatrom!
